name: am_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - jupyter
  - conda-forge::arch-py
  - pandas-datareader
  - yfinance
  - pip
  - pip:
    - black